name: build

on:
    push:
        branches: ["*"]
    pull_request_target:
        branches: [main]
    workflow_dispatch:

env:
    CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
    CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
    SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}

jobs:
    notify_start:
        runs-on: ubuntu-latest
        steps:
            - name: Notify CI channel start
              uses: voxmedia/github-action-slack-notify-build@v1
              with:
                  channel: ci
                  color: "#3278BD"
                  status: STARTED
    build:
        runs-on: ${{matrix.os}}
        needs: [notify_start]
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                node:
                    - 14.15.5
        steps:
            - uses: actions/checkout@v2

            - name: Setup node ${{matrix.node}}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{matrix.node}}

            - name: npm install
              run: npm install

            - name: npm run test
              run: npm run test:coverage

            - name: Upload to codecov
              uses: codecov/codecov-action@v1

    notify_success:
        runs-on: ubuntu-latest
        needs: [build]
        if: success()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              with:
                  channel: ci
                  color: good
                  status: SUCCESS

    notify_failure:
        runs-on: ubuntu-latest
        needs: [build]
        if: failure()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              with:
                  channel: ci
                  color: danger
                  status: FAILED
