on:
    release:
        types: [published]

env:
    SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}

jobs:
    notify_start:
        runs-on: ubuntu-latest
        steps:
            - name: Notify CI channel start
              uses: voxmedia/github-action-slack-notify-build@v1
              with:
                  channel: ci
                  color: "#3278BD"
                  status: STARTED

    publish:
        runs-on: ubuntu-latest
        needs: [notify_start]
        steps:
            - uses: actions/checkout@v2

            - name: Setup node 14.15.5
              uses: actions/setup-node@v2
              with:
                  node-version: 14.15.5

            - name: npm install
              run: npm install

            - name: npm publish
              run: npm publish

    notify_success:
        runs-on: ubuntu-latest
        needs: [build]
        if: success()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              with:
                  channel: ci
                  color: good
                  status: SUCCESS

    notify_failure:
        runs-on: ubuntu-latest
        needs: [build]
        if: failure()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              with:
                  channel: ci
                  color: danger
                  status: FAILED
