name: publish

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version to publish"
                required: true

env:
    SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}

jobs:
    notify_start:
        runs-on: ubuntu-latest
        steps:
            - name: Notify CI channel start
              uses: voxmedia/github-action-slack-notify-build@v1
              with:
                  channel: ci
                  color: "#3278BD"
                  status: STARTED

    publish:
        runs-on: ubuntu-latest
        needs: [notify_start]
        steps:
            - uses: actions/checkout@v2

            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                  token: ${{secrets.GITHUB_TOKEN}}

            - name: Setup node 14.15.5
              uses: actions/setup-node@v2
              with:
                  node-version: 14.15.5
                  registry-url: "https://registry.npmjs.org"

            - name: npm version
              run: npm version ${{github.event.inputs.version}}

            - name: npm install
              run: npm install

            - name: npm publish
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{secrets.NPM_TOKEN}}

            - name: git commit & push
              run: |
                  git status
                  git add .
                  git commit --amend --no-edit
                  git push
                  git push --tags

    notify_success:
        runs-on: ubuntu-latest
        needs: [publish]
        if: success()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              with:
                  channel: ci
                  color: good
                  status: SUCCESS

    notify_failure:
        runs-on: ubuntu-latest
        needs: [publish]
        if: failure()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              with:
                  channel: ci
                  color: danger
                  status: FAILED
